spring:
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
camel:
  springboot:
    name: camel-order-saga
logging:
  level:
    org.apache.camel.saga: DEBUG
